all:

ceres: FORCE
	docker build --no-cache -f Dockerfile.ceres \
		-t dyne/devuan:ceres \
		--force-rm .

excalibur: FORCE
	docker build --no-cache -f Dockerfile.excalibur \
		-t dyne/devuan:excalibur \
		--force-rm .

daedalus: FORCE
	docker build --no-cache -f Dockerfile.daedalus \
		-t dyne/devuan:daedalus \
		--force-rm .

chimaera: FORCE
	docker build --no-cache -f Dockerfile.chimaera \
		-t dyne/devuan:chimaera \
		--force-rm .

beowulf: FORCE
	docker build --no-cache -f Dockerfile.beowulf \
		-t dyne/devuan:beowulf \
		--force-rm .

ascii: FORCE
	docker build --no-cache -f Dockerfile.ascii \
		-t dyne/devuan:ascii \
		--force-rm .

jessie: FORCE
	docker build --no-cache -f Dockerfile.jessie \
		-t dyne/devuan:jessie \
		--force-rm .

ceres-debuild: FORCE
	docker build --no-cache -f Dockerfile.ceres-debuild \
		-t dyne/devuan:ceres-debuild \
		--force-rm .

beowulf-debuild: FORCE
	docker build --no-cache -f Dockerfile.beowulf-debuild \
		-t dyne/devuan:beowulf-debuild \
		--force-rm .

ascii-debuild: FORCE
	docker build --no-cache -f Dockerfile.ascii-debuild \
		-t dyne/devuan:ascii-debuild \
		--force-rm .

FORCE:
