#!/bin/sh

# run to generate almost identical dockerfiles from a single template
# Docker.template and Docker.template-debuild

for i in jessie ascii beowulf chimaera daedalus excalibur ceres; do
	echo "$i"
	sed "s/%REL%/${i}/g" Dockerfile.template > Dockerfile.${i};
	sed "s/%REL%/${i}/g" Dockerfile.template-debuild > Dockerfile.${i}-debuild;

	sed -i -e "s/%TINI%/v0.19.0/" Dockerfile.${i}
	sed -i -e "s/%TINI%/v0.19.0/" Dockerfile.${i}-debuild
done
